name: AsureEnforcement
version: '1.0'
author: SaintQd
main: org.saintqd.asureenforcement.AsureEnforcement
api-version: '26.2'
description: AsureEnforcement Plugin
dependencies:
  server:
    AsureLib:
      load: BEFORE
      required: true